package uwu.narumi.deobfuscator.core.other.impl.phantom;

import org.objectweb.asm.tree.LdcInsnNode;
import uwu.narumi.deobfuscator.api.asm.MethodContext;
import uwu.narumi.deobfuscator.api.asm.matcher.Match;
import uwu.narumi.deobfuscator.api.asm.matcher.group.SequenceMatch;
import uwu.narumi.deobfuscator.api.asm.matcher.impl.MethodMatch;
import uwu.narumi.deobfuscator.api.asm.matcher.impl.StringMatch;
import uwu.narumi.deobfuscator.api.transformer.Transformer;

public class PhantomStringTransformer extends Transformer
{
  private static final Match DECRYPTION_CALL =
      SequenceMatch.of(
          StringMatch.of().capture("str"),
          MethodMatch.invokeStatic().owner("hu").name("fk").desc("(Ljava/lang/String;)Ljava/lang/String;")
      );

  @Override
  protected void transform() throws Exception
  {
    this.scopedClasses().forEach(clazz -> {
      clazz.methods().forEach(methodNode -> {
        DECRYPTION_CALL.findAllMatches(MethodContext.of(clazz, methodNode)).forEach(match -> {
          final LdcInsnNode ldc = new LdcInsnNode(PhantomDecryptor.decrypt(match.captures().get("str").insn().asString()));
          methodNode.instructions.insert(match.insn(), ldc);
          match.removeAll();
          this.markChange();
        });
      });
    });
  }

  @SuppressWarnings("UnnecessaryUnicodeEscape")
  private static final class PhantomDecryptor
  {
    public static final char[] key;

    static
    {
      key = new char[] {
          '\u001f',
          '½',
          '\u00d0',
          '\u00c6',
          '\u00ef',
          'w',
          'J',
          '\u00f7',
          '\u00cb',
          'Z',
          'U',
          '!',
          '\n',
          '\u0099',
          '\u00f0',
          '@',
          'c',
          '\u00d5',
          'f',
          'O',
          '\u00e0',
          'y',
          '\u000e',
          '¥',
          '\u0081',
          '\u00d6',
          '\u00d4',
          '7',
          '\u00fe',
          'K',
          '\u0090',
          '\u00e1',
          '\u00cf',
          '\r',
          '\u001e',
          'q',
          '\b',
          '\u00e6',
          '\u000f',
          '¦',
          'X',
          '\u00f5',
          '\u00ce',
          '\u00c2',
          '\u0093',
          '{',
          ' ',
          ',',
          '\u00c0',
          '©',
          '>',
          '5',
          '\u000b',
          '(',
          '\u0005',
          '<',
          '\u00d7',
          '\u00d8',
          '\u0007',
          'd',
          '\u0014',
          '\u0012',
          '\u0082',
          '$',
          'p',
          'g',
          'M',
          '\u009d',
          '\u0011',
          '§',
          '\"',
          '\u00dc',
          '¸',
          'D',
          '\u00e9',
          '/',
          '\u00de',
          '³',
          '2',
          '\u008c',
          'L',
          '·',
          '\u00fc',
          'Y',
          '\u0089',
          '^',
          '\u0080',
          '\u0019',
          '\u00ea',
          '¼',
          ')',
          '`',
          '\u009b',
          ';',
          '1',
          '\u008a',
          '¿',
          '3',
          '\u0002',
          '\t',
          '_',
          '+',
          'A',
          '\u00ca',
          '\u00dd',
          'j',
          '\u008b',
          '\u0088',
          't',
          '\u00c1',
          '4',
          '\u00c5',
          'G',
          'k',
          '\u0015',
          '8',
          '£',
          '\u00e8',
          '\u0083',
          'F',
          'a',
          '\f',
          '.',
          '\u00eb',
          '\u00d1',
          '\u00db',
          '\u00f8',
          '\u00c4',
          '²',
          '\u0084',
          '\u0003',
          '\u0017',
          '\u0006',
          '«',
          'e',
          'ª',
          '\u0092',
          '0',
          '[',
          '\u00ed',
          '¨',
          '\u009e',
          '\u00f4',
          'Q',
          '\u0085',
          '\u00f3',
          '¡',
          '¬',
          '\u008e',
          'o',
          '\u001b',
          '\u008d',
          '\u0096',
          '\u00cd',
          'E',
          '\u00ec',
          '\u00fa',
          '°',
          '*',
          'P',
          '\u00e2',
          'z',
          '»',
          '6',
          '~',
          '\\',
          '\'',
          '\u00fd',
          '\u009a',
          '\u001d',
          '¹',
          '\u001a',
          '\u00f2',
          '\u00e5',
          'C',
          '\u00c3',
          '¾',
          '#',
          'u',
          '\u00fb',
          'h',
          '\u0087',
          's',
          '\u00ad',
          '}',
          '\u00da',
          '\u0097',
          '\u00ff',
          '\u00e7',
          '\u0018',
          'n',
          '\u0010',
          '\u00e3',
          ':',
          '\u0004',
          '\u00e4',
          '\u0094',
          '?',
          '¯',
          '-',
          '¤',
          '\u001c',
          'W',
          '\u00c7',
          '\u008f',
          '±',
          'x',
          'i',
          '\u0016',
          'B',
          '\u009f',
          '\u00f6',
          'S',
          '%',
          '&',
          '\u007f',
          '\u00d9',
          'H',
          '\u009c',
          '=',
          '¢',
          '\u0013',
          'r',
          '\u00d2',
          ']',
          'v',
          '\u00c8',
          '®',
          '|',
          '\u0095',
          '\u00df',
          '\u00ee',
          'm',
          '\u0086',
          '´',
          'N',
          '\u00c9',
          'º',
          'I',
          '\u0091',
          '\u0098',
          '\u00f9',
          ' ',
          'V',
          'b',
          'R',
          '9',
          'l',
          '\u00d3',
          '¶',
          'µ',
          'T',
          '\u00cc',
          '\u00f1',
          '\0',
          '\u0001'
      };
    }

    public static char getKeyForCharacter(final char c)
    {
      return (c >= '\uc350' && c < 50000 + key.length) ? key[c - '\uc350'] : c;
    }

    public static String decrypt(final String s)
    {
      final char[] charArray = s.toCharArray();
      for (int i = 0; i < charArray.length; ++i)
      {
        charArray[i] = getKeyForCharacter(charArray[i]);
      }
      return new String(charArray);
    }
  }
}